//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoggR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Applications = new HashSet<Application>();
            this.Users = new HashSet<User>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
