//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoggR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.Guid ApiKey { get; set; }
        public System.Guid Account { get; set; }
        public bool Persist { get; set; }
        public int MaxMessages { get; set; }
        public System.DateTime LastMessageDateTime { get; set; }
    
        public virtual Account Account1 { get; set; }
    }
}
