//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLoggR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMessage
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ApiKey { get; set; }
        public string LogLevel { get; set; }
        public string Message { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
